name: Shrine
description: Learn the basics of using Material Components by building a simple app with core components.

environment: 
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.6

  cupertino_icons: ^0.1.0
  shrine_images: 1.1.1
  
  url_launcher: ^6.0.3

  overlay: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/diamond.png
    - assets/hotel_images/0.jpg
    - assets/hotel_images/1.jpg
    - assets/hotel_images/2.jpg
    - assets/hotel_images/3.jpg
    - assets/hotel_images/4.jpg
    - assets/hotel_images/5.jpg
    - assets/hotel_images/6.jpg
    - assets/hotel_images/7.jpg



